// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rjax_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rjax_buffer_from_r
SEXP rjax_buffer_from_r(SEXP client_xptr, SEXP data_sexp, SEXP dims_sexp, SEXP dtype_sexp);
RcppExport SEXP _rjax_rjax_buffer_from_r(SEXP client_xptrSEXP, SEXP data_sexpSEXP, SEXP dims_sexpSEXP, SEXP dtype_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type client_xptr(client_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data_sexp(data_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dims_sexp(dims_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dtype_sexp(dtype_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_buffer_from_r(client_xptr, data_sexp, dims_sexp, dtype_sexp));
    return rcpp_result_gen;
END_RCPP
}
// rjax_buffer_to_r
SEXP rjax_buffer_to_r(SEXP buffer_xptr);
RcppExport SEXP _rjax_rjax_buffer_to_r(SEXP buffer_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type buffer_xptr(buffer_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_buffer_to_r(buffer_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_buffer_shape
SEXP rjax_buffer_shape(SEXP buffer_xptr);
RcppExport SEXP _rjax_rjax_buffer_shape(SEXP buffer_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type buffer_xptr(buffer_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_buffer_shape(buffer_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_client_create
SEXP rjax_client_create(std::string backend);
RcppExport SEXP _rjax_rjax_client_create(SEXP backendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_client_create(backend));
    return rcpp_result_gen;
END_RCPP
}
// rjax_client_platform
SEXP rjax_client_platform(SEXP client_xptr);
RcppExport SEXP _rjax_rjax_client_platform(SEXP client_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type client_xptr(client_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_client_platform(client_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_client_devices
SEXP rjax_client_devices(SEXP client_xptr);
RcppExport SEXP _rjax_rjax_client_devices(SEXP client_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type client_xptr(client_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_client_devices(client_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_compile
SEXP rjax_compile(SEXP client_xptr, SEXP computation_xptr);
RcppExport SEXP _rjax_rjax_compile(SEXP client_xptrSEXP, SEXP computation_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type client_xptr(client_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type computation_xptr(computation_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_compile(client_xptr, computation_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_execute
SEXP rjax_execute(SEXP exec_xptr, SEXP input_buffers_sexp);
RcppExport SEXP _rjax_rjax_execute(SEXP exec_xptrSEXP, SEXP input_buffers_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type exec_xptr(exec_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type input_buffers_sexp(input_buffers_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_execute(exec_xptr, input_buffers_sexp));
    return rcpp_result_gen;
END_RCPP
}
// rjax_builder_new
SEXP rjax_builder_new(std::string name);
RcppExport SEXP _rjax_rjax_builder_new(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_builder_new(name));
    return rcpp_result_gen;
END_RCPP
}
// rjax_parameter
SEXP rjax_parameter(SEXP builder_xptr, int param_num, std::string dtype, Rcpp::IntegerVector dims);
RcppExport SEXP _rjax_rjax_parameter(SEXP builder_xptrSEXP, SEXP param_numSEXP, SEXP dtypeSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type param_num(param_numSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_parameter(builder_xptr, param_num, dtype, dims));
    return rcpp_result_gen;
END_RCPP
}
// rjax_constant_r1
SEXP rjax_constant_r1(SEXP builder_xptr, Rcpp::NumericVector values, std::string dtype);
RcppExport SEXP _rjax_rjax_constant_r1(SEXP builder_xptrSEXP, SEXP valuesSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_constant_r1(builder_xptr, values, dtype));
    return rcpp_result_gen;
END_RCPP
}
// rjax_constant_scalar
SEXP rjax_constant_scalar(SEXP builder_xptr, double value, std::string dtype);
RcppExport SEXP _rjax_rjax_constant_scalar(SEXP builder_xptrSEXP, SEXP valueSEXP, SEXP dtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_constant_scalar(builder_xptr, value, dtype));
    return rcpp_result_gen;
END_RCPP
}
// rjax_add
SEXP rjax_add(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_add(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_add(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_sub
SEXP rjax_sub(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_sub(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_sub(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_mul
SEXP rjax_mul(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_mul(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_mul(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_div
SEXP rjax_div(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_div(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_div(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_neg
SEXP rjax_neg(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_neg(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_neg(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_abs
SEXP rjax_abs(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_abs(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_abs(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_exp
SEXP rjax_exp(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_exp(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_exp(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_log
SEXP rjax_log(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_log(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_log(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_sqrt
SEXP rjax_sqrt(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_sqrt(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_sqrt(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_tanh
SEXP rjax_tanh(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_tanh(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_tanh(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_dot
SEXP rjax_dot(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_dot(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_dot(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_transpose
SEXP rjax_transpose(SEXP op_xptr, Rcpp::IntegerVector permutation);
RcppExport SEXP _rjax_rjax_transpose(SEXP op_xptrSEXP, SEXP permutationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type permutation(permutationSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_transpose(op_xptr, permutation));
    return rcpp_result_gen;
END_RCPP
}
// rjax_reshape
SEXP rjax_reshape(SEXP op_xptr, Rcpp::IntegerVector new_dims);
RcppExport SEXP _rjax_rjax_reshape(SEXP op_xptrSEXP, SEXP new_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type new_dims(new_dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_reshape(op_xptr, new_dims));
    return rcpp_result_gen;
END_RCPP
}
// rjax_pow
SEXP rjax_pow(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_pow(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_pow(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_sin
SEXP rjax_sin(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_sin(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_sin(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_cos
SEXP rjax_cos(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_cos(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_cos(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_sign
SEXP rjax_sign(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_sign(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_sign(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_max
SEXP rjax_max(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_max(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_max(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_min
SEXP rjax_min(SEXP lhs_xptr, SEXP rhs_xptr);
RcppExport SEXP _rjax_rjax_min(SEXP lhs_xptrSEXP, SEXP rhs_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs_xptr(lhs_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs_xptr(rhs_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_min(lhs_xptr, rhs_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_clamp
SEXP rjax_clamp(SEXP min_xptr, SEXP op_xptr, SEXP max_xptr);
RcppExport SEXP _rjax_rjax_clamp(SEXP min_xptrSEXP, SEXP op_xptrSEXP, SEXP max_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type min_xptr(min_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_xptr(max_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_clamp(min_xptr, op_xptr, max_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_select
SEXP rjax_select(SEXP pred_xptr, SEXP on_true_xptr, SEXP on_false_xptr);
RcppExport SEXP _rjax_rjax_select(SEXP pred_xptrSEXP, SEXP on_true_xptrSEXP, SEXP on_false_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pred_xptr(pred_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type on_true_xptr(on_true_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type on_false_xptr(on_false_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_select(pred_xptr, on_true_xptr, on_false_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_op_shape
SEXP rjax_op_shape(SEXP builder_xptr, SEXP op_xptr);
RcppExport SEXP _rjax_rjax_op_shape(SEXP builder_xptrSEXP, SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_op_shape(builder_xptr, op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_broadcast_in_dim
SEXP rjax_broadcast_in_dim(SEXP op_xptr, SEXP out_dims_sexp, SEXP broadcast_dims_sexp);
RcppExport SEXP _rjax_rjax_broadcast_in_dim(SEXP op_xptrSEXP, SEXP out_dims_sexpSEXP, SEXP broadcast_dims_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_dims_sexp(out_dims_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type broadcast_dims_sexp(broadcast_dims_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_broadcast_in_dim(op_xptr, out_dims_sexp, broadcast_dims_sexp));
    return rcpp_result_gen;
END_RCPP
}
// rjax_reduce_sum
SEXP rjax_reduce_sum(SEXP op_xptr, SEXP dims_sexp, SEXP builder_xptr);
RcppExport SEXP _rjax_rjax_reduce_sum(SEXP op_xptrSEXP, SEXP dims_sexpSEXP, SEXP builder_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dims_sexp(dims_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_reduce_sum(op_xptr, dims_sexp, builder_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_constant_broadcast
SEXP rjax_constant_broadcast(SEXP builder_xptr, double value, std::string dtype, SEXP dims_sexp);
RcppExport SEXP _rjax_rjax_constant_broadcast(SEXP builder_xptrSEXP, SEXP valueSEXP, SEXP dtypeSEXP, SEXP dims_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< std::string >::type dtype(dtypeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dims_sexp(dims_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_constant_broadcast(builder_xptr, value, dtype, dims_sexp));
    return rcpp_result_gen;
END_RCPP
}
// rjax_op_builder
SEXP rjax_op_builder(SEXP op_xptr);
RcppExport SEXP _rjax_rjax_op_builder(SEXP op_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type op_xptr(op_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_op_builder(op_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_build
SEXP rjax_build(SEXP builder_xptr);
RcppExport SEXP _rjax_rjax_build(SEXP builder_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_build(builder_xptr));
    return rcpp_result_gen;
END_RCPP
}
// rjax_build_with_root
SEXP rjax_build_with_root(SEXP builder_xptr, SEXP root_xptr);
RcppExport SEXP _rjax_rjax_build_with_root(SEXP builder_xptrSEXP, SEXP root_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type builder_xptr(builder_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type root_xptr(root_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rjax_build_with_root(builder_xptr, root_xptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rjax_rjax_buffer_from_r", (DL_FUNC) &_rjax_rjax_buffer_from_r, 4},
    {"_rjax_rjax_buffer_to_r", (DL_FUNC) &_rjax_rjax_buffer_to_r, 1},
    {"_rjax_rjax_buffer_shape", (DL_FUNC) &_rjax_rjax_buffer_shape, 1},
    {"_rjax_rjax_client_create", (DL_FUNC) &_rjax_rjax_client_create, 1},
    {"_rjax_rjax_client_platform", (DL_FUNC) &_rjax_rjax_client_platform, 1},
    {"_rjax_rjax_client_devices", (DL_FUNC) &_rjax_rjax_client_devices, 1},
    {"_rjax_rjax_compile", (DL_FUNC) &_rjax_rjax_compile, 2},
    {"_rjax_rjax_execute", (DL_FUNC) &_rjax_rjax_execute, 2},
    {"_rjax_rjax_builder_new", (DL_FUNC) &_rjax_rjax_builder_new, 1},
    {"_rjax_rjax_parameter", (DL_FUNC) &_rjax_rjax_parameter, 4},
    {"_rjax_rjax_constant_r1", (DL_FUNC) &_rjax_rjax_constant_r1, 3},
    {"_rjax_rjax_constant_scalar", (DL_FUNC) &_rjax_rjax_constant_scalar, 3},
    {"_rjax_rjax_add", (DL_FUNC) &_rjax_rjax_add, 2},
    {"_rjax_rjax_sub", (DL_FUNC) &_rjax_rjax_sub, 2},
    {"_rjax_rjax_mul", (DL_FUNC) &_rjax_rjax_mul, 2},
    {"_rjax_rjax_div", (DL_FUNC) &_rjax_rjax_div, 2},
    {"_rjax_rjax_neg", (DL_FUNC) &_rjax_rjax_neg, 1},
    {"_rjax_rjax_abs", (DL_FUNC) &_rjax_rjax_abs, 1},
    {"_rjax_rjax_exp", (DL_FUNC) &_rjax_rjax_exp, 1},
    {"_rjax_rjax_log", (DL_FUNC) &_rjax_rjax_log, 1},
    {"_rjax_rjax_sqrt", (DL_FUNC) &_rjax_rjax_sqrt, 1},
    {"_rjax_rjax_tanh", (DL_FUNC) &_rjax_rjax_tanh, 1},
    {"_rjax_rjax_dot", (DL_FUNC) &_rjax_rjax_dot, 2},
    {"_rjax_rjax_transpose", (DL_FUNC) &_rjax_rjax_transpose, 2},
    {"_rjax_rjax_reshape", (DL_FUNC) &_rjax_rjax_reshape, 2},
    {"_rjax_rjax_pow", (DL_FUNC) &_rjax_rjax_pow, 2},
    {"_rjax_rjax_sin", (DL_FUNC) &_rjax_rjax_sin, 1},
    {"_rjax_rjax_cos", (DL_FUNC) &_rjax_rjax_cos, 1},
    {"_rjax_rjax_sign", (DL_FUNC) &_rjax_rjax_sign, 1},
    {"_rjax_rjax_max", (DL_FUNC) &_rjax_rjax_max, 2},
    {"_rjax_rjax_min", (DL_FUNC) &_rjax_rjax_min, 2},
    {"_rjax_rjax_clamp", (DL_FUNC) &_rjax_rjax_clamp, 3},
    {"_rjax_rjax_select", (DL_FUNC) &_rjax_rjax_select, 3},
    {"_rjax_rjax_op_shape", (DL_FUNC) &_rjax_rjax_op_shape, 2},
    {"_rjax_rjax_broadcast_in_dim", (DL_FUNC) &_rjax_rjax_broadcast_in_dim, 3},
    {"_rjax_rjax_reduce_sum", (DL_FUNC) &_rjax_rjax_reduce_sum, 3},
    {"_rjax_rjax_constant_broadcast", (DL_FUNC) &_rjax_rjax_constant_broadcast, 4},
    {"_rjax_rjax_op_builder", (DL_FUNC) &_rjax_rjax_op_builder, 1},
    {"_rjax_rjax_build", (DL_FUNC) &_rjax_rjax_build, 1},
    {"_rjax_rjax_build_with_root", (DL_FUNC) &_rjax_rjax_build_with_root, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rjax(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
