# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rjax_buffer_from_r <- function(client_xptr, data_sexp, dims_sexp, dtype_sexp) {
    .Call(`_rjax_rjax_buffer_from_r`, client_xptr, data_sexp, dims_sexp, dtype_sexp)
}

rjax_buffer_to_r <- function(buffer_xptr) {
    .Call(`_rjax_rjax_buffer_to_r`, buffer_xptr)
}

rjax_buffer_shape <- function(buffer_xptr) {
    .Call(`_rjax_rjax_buffer_shape`, buffer_xptr)
}

rjax_client_create <- function() {
    .Call(`_rjax_rjax_client_create`)
}

rjax_client_platform <- function(client_xptr) {
    .Call(`_rjax_rjax_client_platform`, client_xptr)
}

rjax_client_devices <- function(client_xptr) {
    .Call(`_rjax_rjax_client_devices`, client_xptr)
}

rjax_compile <- function(client_xptr, computation_xptr) {
    .Call(`_rjax_rjax_compile`, client_xptr, computation_xptr)
}

rjax_execute <- function(exec_xptr, input_buffers_sexp) {
    .Call(`_rjax_rjax_execute`, exec_xptr, input_buffers_sexp)
}

rjax_builder_new <- function(name) {
    .Call(`_rjax_rjax_builder_new`, name)
}

rjax_parameter <- function(builder_xptr, param_num, dtype, dims) {
    .Call(`_rjax_rjax_parameter`, builder_xptr, param_num, dtype, dims)
}

rjax_constant_r1 <- function(builder_xptr, values, dtype) {
    .Call(`_rjax_rjax_constant_r1`, builder_xptr, values, dtype)
}

rjax_constant_scalar <- function(builder_xptr, value, dtype) {
    .Call(`_rjax_rjax_constant_scalar`, builder_xptr, value, dtype)
}

rjax_add <- function(lhs_xptr, rhs_xptr) {
    .Call(`_rjax_rjax_add`, lhs_xptr, rhs_xptr)
}

rjax_sub <- function(lhs_xptr, rhs_xptr) {
    .Call(`_rjax_rjax_sub`, lhs_xptr, rhs_xptr)
}

rjax_mul <- function(lhs_xptr, rhs_xptr) {
    .Call(`_rjax_rjax_mul`, lhs_xptr, rhs_xptr)
}

rjax_div <- function(lhs_xptr, rhs_xptr) {
    .Call(`_rjax_rjax_div`, lhs_xptr, rhs_xptr)
}

rjax_neg <- function(op_xptr) {
    .Call(`_rjax_rjax_neg`, op_xptr)
}

rjax_abs <- function(op_xptr) {
    .Call(`_rjax_rjax_abs`, op_xptr)
}

rjax_exp <- function(op_xptr) {
    .Call(`_rjax_rjax_exp`, op_xptr)
}

rjax_log <- function(op_xptr) {
    .Call(`_rjax_rjax_log`, op_xptr)
}

rjax_sqrt <- function(op_xptr) {
    .Call(`_rjax_rjax_sqrt`, op_xptr)
}

rjax_tanh <- function(op_xptr) {
    .Call(`_rjax_rjax_tanh`, op_xptr)
}

rjax_dot <- function(lhs_xptr, rhs_xptr) {
    .Call(`_rjax_rjax_dot`, lhs_xptr, rhs_xptr)
}

rjax_transpose <- function(op_xptr, permutation) {
    .Call(`_rjax_rjax_transpose`, op_xptr, permutation)
}

rjax_reshape <- function(op_xptr, new_dims) {
    .Call(`_rjax_rjax_reshape`, op_xptr, new_dims)
}

rjax_build <- function(builder_xptr) {
    .Call(`_rjax_rjax_build`, builder_xptr)
}

rjax_build_with_root <- function(builder_xptr, root_xptr) {
    .Call(`_rjax_rjax_build_with_root`, builder_xptr, root_xptr)
}

